#!/usr/bin/env python3
"""Safely maintain the plugin manifest and generated requirements file.

This helper intentionally uses only the Python standard library.  plugin.sh
runs it in an isolated Docker container, so the host does not need Python or
jq installed.
"""

from __future__ import annotations

import json
import os
import re
import sys
import tempfile
from pathlib import Path
from typing import Any


MANIFEST_NAME = "third_party_plugins.json"
REQUIREMENTS_NAME = "requirements-plugins.txt"
REQUIREMENTS_HEADER = (
    "# Managed by plugin.sh/plugin.ps1. Do not edit this file while using "
    "the manager."
)

_DIST_NAME = r"[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?"
_EXTRA_NAME = r"[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?"
_VERSION = r"[A-Za-z0-9][A-Za-z0-9.*+!_-]*"
_OPERATOR = r"(?:===|==|~=|!=|>=|<=|>|<)"
PACKAGE_SPEC_RE = re.compile(
    rf"(?P<name>{_DIST_NAME})(?:\[(?:{_EXTRA_NAME})(?:,(?:{_EXTRA_NAME}))*\])?"
    rf"(?:{_OPERATOR}{_VERSION}(?:,{_OPERATOR}{_VERSION})*)?"
)
MODULE_RE = re.compile(
    r"[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*"
)


class ManifestError(Exception):
    """An expected, user-facing manifest error."""


def parse_package_spec(spec: str) -> tuple[str, str]:
    cleaned = spec.strip()
    match = PACKAGE_SPEC_RE.fullmatch(cleaned)
    if match is None:
        raise ManifestError(
            f"unsupported package specification {spec!r}; use a package name "
            "or a quoted version such as 'nonebot-plugin-example==1.2.3'"
        )
    return cleaned, match.group("name")


def normalize_distribution(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).strip("-").lower()


def validate_module(module: str) -> str:
    cleaned = module.strip()
    if MODULE_RE.fullmatch(cleaned) is None:
        raise ManifestError(f"invalid Python module name {module!r}")
    return cleaned


def load_entries(manifest_path: Path) -> list[dict[str, str]]:
    if not manifest_path.exists():
        return []
    if not manifest_path.is_file():
        raise ManifestError(f"{manifest_path.name} is not a regular file")

    try:
        raw = manifest_path.read_text(encoding="utf-8-sig")
    except (OSError, UnicodeError) as exc:
        raise ManifestError(f"cannot read {manifest_path.name}: {exc}") from exc

    if not raw.strip():
        return []
    try:
        document: Any = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ManifestError(
            f"cannot parse {manifest_path.name}: line {exc.lineno}, "
            f"column {exc.colno}: {exc.msg}"
        ) from exc

    if not isinstance(document, dict):
        raise ManifestError(f"{manifest_path.name} must contain a JSON object")
    plugins = document.get("plugins")
    if not isinstance(plugins, list):
        raise ManifestError(
            f"{manifest_path.name} must contain a 'plugins' JSON array"
        )

    entries: list[dict[str, str]] = []
    seen_packages: set[str] = set()
    seen_modules: set[str] = set()
    for index, item in enumerate(plugins, start=1):
        if not isinstance(item, dict):
            raise ManifestError(f"plugin entry {index} must be a JSON object")
        package = item.get("package")
        module = item.get("module")
        if not isinstance(package, str) or not isinstance(module, str):
            raise ManifestError(
                f"plugin entry {index} must contain string package and module fields"
            )
        cleaned_package, distribution = parse_package_spec(package)
        cleaned_module = validate_module(module)
        normalized_package = normalize_distribution(distribution)
        if normalized_package in seen_packages:
            raise ManifestError(f"duplicate package in manifest: {distribution}")
        if cleaned_module.lower() in seen_modules:
            raise ManifestError(f"duplicate module in manifest: {cleaned_module}")
        seen_packages.add(normalized_package)
        seen_modules.add(cleaned_module.lower())
        entries.append({"package": cleaned_package, "module": cleaned_module})

    return entries


def atomic_write(path: Path, data: bytes, mode: int) -> None:
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary_path, mode)
        os.replace(temporary_path, path)
        try:
            directory_flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0)
            directory_fd = os.open(path.parent, directory_flags)
        except OSError:
            return
        try:
            os.fsync(directory_fd)
        except OSError:
            pass
        finally:
            os.close(directory_fd)
    finally:
        try:
            temporary_path.unlink()
        except FileNotFoundError:
            pass


def snapshot(path: Path) -> tuple[bool, bytes, int]:
    if not path.exists():
        return False, b"", 0o644
    if not path.is_file():
        raise ManifestError(f"{path.name} is not a regular file")
    try:
        return True, path.read_bytes(), path.stat().st_mode & 0o777
    except OSError as exc:
        raise ManifestError(f"cannot snapshot {path.name}: {exc}") from exc


def restore(path: Path, state: tuple[bool, bytes, int]) -> None:
    existed, data, mode = state
    if existed:
        atomic_write(path, data, mode)
    else:
        try:
            path.unlink()
        except FileNotFoundError:
            pass


def write_entries(root: Path, entries: list[dict[str, str]]) -> None:
    manifest_path = root / MANIFEST_NAME
    requirements_path = root / REQUIREMENTS_NAME
    ordered = sorted(
        entries,
        key=lambda entry: (
            normalize_distribution(parse_package_spec(entry["package"])[1]),
            entry["module"].lower(),
        ),
    )
    manifest_bytes = (
        json.dumps({"plugins": ordered}, ensure_ascii=False, indent=2) + "\n"
    ).encode("utf-8")
    requirement_text = "\n".join(
        [REQUIREMENTS_HEADER, *(entry["package"] for entry in ordered), ""]
    )
    requirements_bytes = requirement_text.encode("utf-8")

    manifest_state = snapshot(manifest_path)
    requirements_state = snapshot(requirements_path)
    try:
        atomic_write(manifest_path, manifest_bytes, manifest_state[2])
        atomic_write(requirements_path, requirements_bytes, requirements_state[2])
    except Exception as write_error:
        restore_errors: list[str] = []
        for path, state in (
            (manifest_path, manifest_state),
            (requirements_path, requirements_state),
        ):
            try:
                restore(path, state)
            except Exception as exc:  # best effort; retain the original failure
                restore_errors.append(f"{path.name}: {exc}")
        detail = ""
        if restore_errors:
            detail = "; restoration also failed for " + ", ".join(restore_errors)
        raise ManifestError(f"cannot update plugin files: {write_error}{detail}") from write_error


def add_entry(root: Path, package_spec: str, module: str | None) -> None:
    cleaned_spec, distribution = parse_package_spec(package_spec)
    normalized = normalize_distribution(distribution)
    if module is None:
        module = distribution.lower().replace("-", "_").replace(".", "_")
    cleaned_module = validate_module(module)

    entries = load_entries(root / MANIFEST_NAME)
    updated: list[dict[str, str]] = []
    replaced = False
    for entry in entries:
        existing_distribution = parse_package_spec(entry["package"])[1]
        if normalize_distribution(existing_distribution) == normalized:
            updated.append({"package": cleaned_spec, "module": cleaned_module})
            replaced = True
        elif entry["module"].lower() == cleaned_module.lower():
            raise ManifestError(
                f"module {cleaned_module!r} is already registered by "
                f"package {entry['package']!r}"
            )
        else:
            updated.append(entry)
    if not replaced:
        updated.append({"package": cleaned_spec, "module": cleaned_module})
    write_entries(root, updated)


def remove_entry(root: Path, target: str) -> None:
    cleaned_target = target.strip()
    if not cleaned_target:
        raise ManifestError("package or module is required")
    entries = load_entries(root / MANIFEST_NAME)

    package_target: str | None
    try:
        package_target = normalize_distribution(parse_package_spec(cleaned_target)[1])
    except ManifestError:
        package_target = None

    package_matches: list[dict[str, str]] = []
    if package_target is not None:
        package_matches = [
            entry
            for entry in entries
            if normalize_distribution(parse_package_spec(entry["package"])[1])
            == package_target
        ]
    if package_matches:
        removed_ids = {id(entry) for entry in package_matches}
        remaining = [entry for entry in entries if id(entry) not in removed_ids]
    else:
        module_matches = [
            entry for entry in entries if entry["module"] == cleaned_target
        ]
        if not module_matches:
            raise ManifestError(f"plugin {cleaned_target!r} is not configured")
        removed_ids = {id(entry) for entry in module_matches}
        remaining = [entry for entry in entries if id(entry) not in removed_ids]

    write_entries(root, remaining)


def list_entries(root: Path) -> None:
    entries = load_entries(root / MANIFEST_NAME)
    if not entries:
        print("No third-party plugins are configured.")
        return
    package_width = max(len("PACKAGE"), *(len(entry["package"]) for entry in entries))
    print(f"{'PACKAGE':<{package_width}}  MODULE")
    print(f"{'-' * package_width}  {'-' * len('MODULE')}")
    for entry in entries:
        print(f"{entry['package']:<{package_width}}  {entry['module']}")


def usage() -> str:
    return (
        "usage: plugin_manifest.py ROOT add PACKAGE [MODULE]\n"
        "       plugin_manifest.py ROOT remove PACKAGE_OR_MODULE\n"
        "       plugin_manifest.py ROOT list"
    )


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        raise ManifestError(usage())
    root = Path(argv[0]).resolve()
    if not root.is_dir():
        raise ManifestError(f"working directory does not exist: {root}")
    action = argv[1]
    arguments = argv[2:]
    if action == "add" and len(arguments) in (1, 2):
        add_entry(root, arguments[0], arguments[1] if len(arguments) == 2 else None)
    elif action == "remove" and len(arguments) == 1:
        remove_entry(root, arguments[0])
    elif action == "list" and not arguments:
        list_entries(root)
    else:
        raise ManifestError(usage())
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except ManifestError as exc:
        print(f"plugin manifest error: {exc}", file=sys.stderr)
        raise SystemExit(2)
