[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet("add", "remove", "list", "rebuild", "help")]
    [string]$Action = "help",

    [Parameter(Position = 1)]
    [string]$Package,

    [Parameter(Position = 2)]
    [string]$Module,

    [switch]$NoBuild
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$projectDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$composeFile = Join-Path $projectDir "compose.yaml"
$manifestPath = Join-Path $projectDir "third_party_plugins.json"
$pluginRequirementsPath = Join-Path $projectDir "requirements-plugins.txt"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )

    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

function Get-PackageNameFromSpec {
    param([Parameter(Mandatory = $true)][string]$Spec)

    $trimmed = $Spec.Trim()
    $versionPart = "(?:===|==|~=|!=|>=|<=|>|<)[A-Za-z0-9][A-Za-z0-9.*+!_-]*"
    $pattern = "^([A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[A-Za-z0-9._,-]+\])?(?:$versionPart(?:,$versionPart)*)?$"
    if ($trimmed -notmatch $pattern) {
        throw "Unsupported package specification '$Spec'. Use a package name or a quoted version such as 'nonebot-plugin-example==1.2.3'."
    }

    return $Matches[1]
}

function Normalize-PackageName {
    param([Parameter(Mandatory = $true)][string]$Name)
    return (($Name.ToLowerInvariant() -replace "[-_.]+", "-").Trim("-"))
}

function Get-PluginEntries {
    if (-not (Test-Path -LiteralPath $manifestPath)) {
        return @()
    }

    $raw = [System.IO.File]::ReadAllText($manifestPath)
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return @()
    }

    try {
        $manifest = $raw | ConvertFrom-Json
    }
    catch {
        throw "Cannot parse $manifestPath as JSON: $($_.Exception.Message)"
    }

    if ($null -eq $manifest.plugins) {
        return @()
    }

    $entries = @()
    foreach ($entry in @($manifest.plugins)) {
        if ([string]::IsNullOrWhiteSpace([string]$entry.package) -or
            [string]::IsNullOrWhiteSpace([string]$entry.module)) {
            throw "Each entry in $manifestPath must contain package and module fields."
        }
        $entries += [PSCustomObject]@{
            package = [string]$entry.package
            module  = [string]$entry.module
        }
    }
    return $entries
}

function Write-PluginEntries {
    param([Parameter(Mandatory = $true)][AllowEmptyCollection()][object[]]$Entries)

    $sortedEntries = @($Entries | Sort-Object -Property package)
    $manifest = [ordered]@{ plugins = @($sortedEntries) }
    $manifestJson = $manifest | ConvertTo-Json -Depth 4

    $requirementLines = @(
        "# Managed by plugin.ps1. Do not edit this file while using the manager."
    )
    foreach ($entry in $sortedEntries) {
        $requirementLines += [string]$entry.package
    }

    $temporarySuffix = [Guid]::NewGuid().ToString("N")
    $temporaryManifest = Join-Path $projectDir ".third_party_plugins.$temporarySuffix.tmp"
    $temporaryRequirements = Join-Path $projectDir ".requirements-plugins.$temporarySuffix.tmp"
    try {
        Write-Utf8NoBom -Path $temporaryManifest -Content ($manifestJson + "`n")
        Write-Utf8NoBom -Path $temporaryRequirements -Content (($requirementLines -join "`n") + "`n")
        Move-Item -LiteralPath $temporaryManifest -Destination $manifestPath -Force
        Move-Item -LiteralPath $temporaryRequirements -Destination $pluginRequirementsPath -Force
    }
    finally {
        if (Test-Path -LiteralPath $temporaryManifest) {
            Remove-Item -LiteralPath $temporaryManifest -Force
        }
        if (Test-Path -LiteralPath $temporaryRequirements) {
            Remove-Item -LiteralPath $temporaryRequirements -Force
        }
    }
}

function Get-FileSnapshot {
    param([Parameter(Mandatory = $true)][string]$Path)
    return [PSCustomObject]@{
        Exists  = Test-Path -LiteralPath $Path
        Content = if (Test-Path -LiteralPath $Path) { [System.IO.File]::ReadAllText($Path) } else { "" }
    }
}

function Restore-FileSnapshot {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)]$Snapshot
    )

    if ($Snapshot.Exists) {
        Write-Utf8NoBom -Path $Path -Content ([string]$Snapshot.Content)
    }
    elseif (Test-Path -LiteralPath $Path) {
        Remove-Item -LiteralPath $Path -Force
    }
}

function Resolve-DockerExe {
    $dockerCommand = Get-Command docker.exe -ErrorAction SilentlyContinue
    if ($null -ne $dockerCommand) {
        return $dockerCommand.Source
    }

    if (-not [string]::IsNullOrWhiteSpace($env:LOCALAPPDATA)) {
        $fallback = Join-Path $env:LOCALAPPDATA "Programs\DockerDesktop\resources\bin\docker.exe"
        if (Test-Path -LiteralPath $fallback) {
            return $fallback
        }
    }

    if (-not [string]::IsNullOrWhiteSpace($env:ProgramFiles)) {
        $systemFallback = Join-Path $env:ProgramFiles "Docker\Docker\resources\bin\docker.exe"
        if (Test-Path -LiteralPath $systemFallback) {
            return $systemFallback
        }
    }

    throw "docker.exe was not found. Start Docker Desktop or add Docker to PATH."
}

function Invoke-Compose {
    param([Parameter(Mandatory = $true)][string[]]$Arguments)

    & $script:dockerExe compose --project-directory $projectDir --file $composeFile @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose $($Arguments -join ' ') failed with exit code $LASTEXITCODE."
    }
}

function Wait-BotHealthy {
    for ($attempt = 0; $attempt -lt 45; $attempt++) {
        $idOutput = & $script:dockerExe compose --project-directory $projectDir --file $composeFile ps --all --quiet qqbot
        if ($LASTEXITCODE -ne 0) {
            throw "Unable to query the qqbot container."
        }

        $containerId = (@($idOutput) -join "`n").Trim()
        if (-not [string]::IsNullOrWhiteSpace($containerId)) {
            $statusOutput = & $script:dockerExe inspect --format "{{.State.Status}}|{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}" $containerId
            if ($LASTEXITCODE -eq 0) {
                $status = (@($statusOutput) -join "`n").Trim()
                $statusParts = $status -split "\|", 2
                $runtimeStatus = $statusParts[0]
                $healthStatus = $statusParts[1]
                if ($runtimeStatus -eq "running" -and $healthStatus -in @("healthy", "none")) {
                    Write-Host "QQ bot is healthy." -ForegroundColor Green
                    return
                }
                if ($runtimeStatus -in @("restarting", "exited", "dead") -or $healthStatus -eq "unhealthy") {
                    break
                }
            }
        }
        Start-Sleep -Seconds 2
    }

    & $script:dockerExe compose --project-directory $projectDir --file $composeFile logs --no-color --tail 100 qqbot
    throw "QQ bot did not become healthy. The last 100 log lines are shown above."
}

function Build-And-Restart {
    Invoke-Compose -Arguments @("build", "qqbot")
    Invoke-Compose -Arguments @("up", "-d", "--force-recreate", "qqbot")
    Wait-BotHealthy
}

function Invoke-ManagedChange {
    param([Parameter(Mandatory = $true)][AllowEmptyCollection()][object[]]$Entries)

    $manifestSnapshot = Get-FileSnapshot -Path $manifestPath
    $requirementsSnapshot = Get-FileSnapshot -Path $pluginRequirementsPath
    try {
        Write-PluginEntries -Entries $Entries
    }
    catch {
        Restore-FileSnapshot -Path $manifestPath -Snapshot $manifestSnapshot
        Restore-FileSnapshot -Path $pluginRequirementsPath -Snapshot $requirementsSnapshot
        throw
    }

    if ($NoBuild) {
        Write-Host "Plugin files updated. Run '.\plugin.cmd rebuild' when ready." -ForegroundColor Yellow
        return
    }

    $buildCompleted = $false
    $restartAttempted = $false
    try {
        Invoke-Compose -Arguments @("build", "qqbot")
        $buildCompleted = $true
        $restartAttempted = $true
        Invoke-Compose -Arguments @("up", "-d", "--force-recreate", "qqbot")
        Wait-BotHealthy
    }
    catch {
        $originalError = $_
        Write-Warning "Plugin change failed. Restoring the previous plugin files."
        Restore-FileSnapshot -Path $manifestPath -Snapshot $manifestSnapshot
        Restore-FileSnapshot -Path $pluginRequirementsPath -Snapshot $requirementsSnapshot

        if ($buildCompleted) {
            try {
                Invoke-Compose -Arguments @("build", "qqbot")
                if ($restartAttempted) {
                    Invoke-Compose -Arguments @("up", "-d", "--force-recreate", "qqbot")
                    Wait-BotHealthy
                }
                Write-Host "Previous plugin configuration restored." -ForegroundColor Yellow
            }
            catch {
                Write-Warning "Automatic container rollback also failed. Check Docker Desktop and run '.\plugin.cmd rebuild'."
            }
        }
        throw $originalError
    }
}

function Show-Help {
    @"
NoneBot Docker plugin manager

Usage:
  .\plugin.cmd add <pip-package> [python-module]
  .\plugin.cmd remove <pip-package-or-module>
  .\plugin.cmd list
  .\plugin.cmd rebuild

Examples:
  .\plugin.cmd add nonebot-plugin-apscheduler
  .\plugin.cmd add "some-package==1.2.3" some_python_module
  .\plugin.cmd remove nonebot-plugin-apscheduler

The module name is normally derived by replacing '-' with '_'. Supply it
explicitly when the plugin documentation shows a different import name.
Use -NoBuild with add/remove to update files without rebuilding immediately.
"@ | Write-Host
}

$script:dockerExe = $null

switch ($Action) {
    "help" {
        Show-Help
    }
    "list" {
        $entries = @(Get-PluginEntries)
        if ($entries.Count -eq 0) {
            Write-Host "No third-party plugins are configured."
        }
        else {
            $entries | Format-Table -AutoSize package, module
        }
    }
    "add" {
        if ([string]::IsNullOrWhiteSpace($Package)) {
            throw "Package is required. Example: .\plugin.cmd add nonebot-plugin-apscheduler"
        }

        $distributionName = Get-PackageNameFromSpec -Spec $Package
        $normalizedName = Normalize-PackageName -Name $distributionName
        if ([string]::IsNullOrWhiteSpace($Module)) {
            $Module = ($distributionName.ToLowerInvariant() -replace "[-.]", "_")
        }
        if ($Module -notmatch "^[A-Za-z_][A-Za-z0-9_.]*$") {
            throw "Invalid Python module name '$Module'."
        }

        $entries = @(Get-PluginEntries)
        $updatedEntries = @()
        $replaced = $false
        foreach ($entry in $entries) {
            $entryName = Normalize-PackageName -Name (Get-PackageNameFromSpec -Spec $entry.package)
            if ($entryName -eq $normalizedName) {
                $updatedEntries += [PSCustomObject]@{ package = $Package.Trim(); module = $Module }
                $replaced = $true
            }
            elseif ($entry.module -eq $Module) {
                throw "Module '$Module' is already registered by package '$($entry.package)'."
            }
            else {
                $updatedEntries += $entry
            }
        }
        if (-not $replaced) {
            $updatedEntries += [PSCustomObject]@{ package = $Package.Trim(); module = $Module }
        }

        if (-not $NoBuild) {
            $script:dockerExe = Resolve-DockerExe
        }
        Invoke-ManagedChange -Entries $updatedEntries
        if ($NoBuild) {
            Write-Host "Plugin '$Module' registered; rebuild is pending." -ForegroundColor Yellow
        }
        else {
            Write-Host "Plugin '$Module' installed and loaded." -ForegroundColor Green
        }
    }
    "remove" {
        if ([string]::IsNullOrWhiteSpace($Package)) {
            throw "Package or module is required. Example: .\plugin.cmd remove nonebot-plugin-apscheduler"
        }

        $target = $Package.Trim()
        try {
            $targetName = Normalize-PackageName -Name (Get-PackageNameFromSpec -Spec $target)
        }
        catch {
            $targetName = Normalize-PackageName -Name $target
        }

        $entries = @(Get-PluginEntries)
        $remaining = @()
        $removed = @()
        foreach ($entry in $entries) {
            $entryName = Normalize-PackageName -Name (Get-PackageNameFromSpec -Spec $entry.package)
            if ($entryName -eq $targetName -or $entry.module -eq $target) {
                $removed += $entry
            }
            else {
                $remaining += $entry
            }
        }
        if ($removed.Count -eq 0) {
            throw "Plugin '$target' is not configured."
        }

        if (-not $NoBuild) {
            $script:dockerExe = Resolve-DockerExe
        }
        Invoke-ManagedChange -Entries $remaining
        if ($NoBuild) {
            Write-Host "Plugin '$($removed[0].module)' removed from the files; rebuild is pending." -ForegroundColor Yellow
        }
        else {
            Write-Host "Plugin '$($removed[0].module)' removed." -ForegroundColor Green
        }
    }
    "rebuild" {
        $script:dockerExe = Resolve-DockerExe
        Build-And-Restart
    }
}
